Add rules for challenges modal
hackclub/v2 pull request #276
Opened 2018-04-21 04:23 UTC by mj66

2018-04-21 07:33 UTC, MaxWofford commented
This looks great! Only thing I think should change is mobile view:

![](https://user-images.githubusercontent.com/5891442/39081745-88606578-44fb-11e8-8ab9-8b9da1f20262.png)

2018-04-21 16:07 UTC, lachlanjc requested changes
Hey, thank you so much for this PR! 🌟 I decided to give _lots_ of feedback on everything, which I hope can be more helpful than overwhelming. The majority of it is stylistic, the only critical thing is running `yarn run fmt` so there's consistent formatting. Also I'm happy to explain anything I wasn't very clear about.

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +const Overlay = Card.extend`
This should be in the Modal component file, it's not related to the /challenge page itself

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +class HelpButton extends Button {
The `.extend` method used elsewhere is actually from styled-components, not React. Since this component is stateless, but may need variables defined before rendering, it should be written like this:

```js
const HelpButton = () => {
  …
  return (
    …
  )
}
```

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +    var ButtonStyle;
Using `var` isn't cool anymore. Use `const` if it's a constant—won't need to be changed—but since here it does, `let`. Both of these are "scoped", so they won't be accessible outside the rendering of `HelpButton`.

Also, don't capitalize variable names—that makes it look like they're React components

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +    return (<Button style={ButtonStyle} f={2}><Icon name="flag" size="20" m={-1} />&ensp;Rules</Button>)
Before any PR can be merged it _must_ have Prettier run, to ensure consistent formatting. Please run `yarn run fmt` and this will magically be easier to read :)

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +    return (<Button style={ButtonStyle} f={2}><Icon name="flag" size="20" m={-1} />&ensp;Rules</Button>)
Also—`size` should be a number (like `size={64}`)

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +    return (<Button style={ButtonStyle} f={2}><Icon name="flag" size="20" m={-1} />&ensp;Rules</Button>)
And instead of an escaped space, give the icon a small margin to the right—`mr={1}`

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +    this.state = { active: false}
While this is a stateful component, it does not have to have a `constructor`. (and just fyi, you don't need to accept props in the constructor/pass them to `super()` unless you need to access them inside this function).

This is shorter:

```js
class Help extends Component {
  this.state = { active: false }

  …
}
```

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +        active: !this.state.active
This is probably going to work with this component, but as a guideline you should never access `this.state` inside `this.setState`. That's because (esp in more complex components) state updates may be batched, and so sometimes `this.state` hasn't actually updated yet. Instead, use a function of `prevState`. See the docs here: https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +      <div style={{width: 100 + "%"}}>
When styling something in this codebase, you want to 1) use DS's styling props, 2) use `styled-components`’s [`.extend`](https://www.styled-components.com/docs/basics#extending-styles) method for adding custom styling to a DS component, or 3) as a last resort, use a `style` attribute.

This one has a prop, so let's use that (`w` is the shorthand of `width`):
```js
<Box w={1}>
  …
</Box>
```

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +        <HelpButton f={2} onClick={this.toggleRules.bind(this)} />
Since `toggleRules` was defined like `toggleRules = () => …`, it's already bound to `this`, so it can just by `{this.toggleRules}`. ✨

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +          <div>
This `<div>` isn't needed, try a React Fragment: https://reactjs.org/docs/react-api.html#reactfragment

I think using `<React.Fragment>` is ugly, so I do `import React, { Component, Fragment } from 'react'` at the top and then can use `<Fragment>`.

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +                    <Heading.h2 align="left" pb={3}>
If you've got several elements that need the same `align`ment, remove it from the children and put it on the parent (in this case, `Container`) for them to inherit.

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +                      Challenge follows Hack Club's <Link href="https://conduct.hackclub.com" target="_blank">Code of Conduct</Link>.
You can see what GitHub does to single quotes :) we don't want any of those in text, as they don't look as nice (see how the quote I just used is straight up-and-down, not slanted with the text). Use rich quotes, like these (on a Mac, <kbd>(shift)+option+brackets</kbd>): `”“‘’`

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +            <Overlay onClick={this.toggleRules.bind(this)} />
again, you can remove `.bind(this)` on these

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +            <Help f={2} bg="info" style={{marginLeft: 47+"%"}} />
As a future contributor to this codebase, I have no clue where "47%" came from. I'm assuming it's like 50%-half the width of the button? but that really depends on your screen size. Add a comment to explain, or use a different way of centering (like left + transform/translate)

2018-04-21 16:07 UTC, lachlanjc commented on src/components/Modal.js
> +  width: 700px;
700px is a kind of an arbitrary number. Try `36rem` or something that a lot of `Container` widths have?

2018-04-21 16:07 UTC, lachlanjc commented on src/pages/challenge.js
> +const mobileMeida = window.matchMedia('(min-width: 800px)');
Assuming you just accidentally misspelled this?

2018-04-22 02:31 UTC, mj66 commented on src/pages/challenge.js
> +const mobileMeida = window.matchMedia('(min-width: 800px)');
Ooooof thanks :))))))

2018-04-22 04:23 UTC, itsmingjie commented on src/pages/challenge.js
> +            <Help f={2} bg="info" style={{marginLeft: 47+"%"}} />
I will completely rewrite how I'm placing the button.

2018-04-22 05:27 UTC, mj66 commented
Thanks, @lachlanjc ! I have tried my best to solve as many things as I can. I'll definitely work on the stylistic issues that I had. Tell me if something still doesn't look right!

2018-04-22 05:36 UTC, lachlanjc commented
Awesome!! I will check this out on my computer tomorrow.

2018-04-22 05:38 UTC, merged