Launch Leaders
hackclub/v2 pull request #407
Opened 2018-09-20 18:48 UTC by lachlanjc

2018-09-21 01:55 UTC, zanedb requested changes

2018-09-21 01:55 UTC, zanedb commented on src/components/home/Header.js
> +          to="https://leaders.hackclub.com/?ref=home"
Shouldn't this be `href="https://leaders.hackclub.com/?ref=home"`?

2018-09-21 01:58 UTC, lachlanjc commented on src/components/home/Header.js
> +          to="https://leaders.hackclub.com/?ref=home"
Yesss thx girl. We were kinda done when we wrote this, lol

2018-09-21 01:59 UTC, zanedb commented on src/components/home/Header.js
> +          to="https://leaders.hackclub.com/?ref=home"
I understand :)

2018-09-22 15:35 UTC, lachlanjc commented
@MaxWofford 👋

2018-09-24 00:21 UTC, maxwofford commented
LGTM

2018-09-24 00:21 UTC, merged

2018-09-24 15:44 UTC, lachlanjc commented
Max, this doesn’t work, it needed to be fixed before merging :)

2018-09-24 17:20 UTC, MaxWofford commented
Published the previous build on Netlify

2018-09-24 19:33 UTC, MaxWofford commented
@lachlanjc will let you handle making a fix, but I like the design. Unclear on why I was originally tagged on this though