Flaggy <Flag/>
hackclub/v2 pull request #576
Opened 2019-09-04 09:17 UTC by thesephist

wat if orpheus wave dat flag when u hover over the logo

![flaggy-flag](https://user-images.githubusercontent.com/5403917/64242264-17337d00-ceba-11e9-83a2-b34a236af258.gif)

2019-09-04 12:44 UTC, lachlanjc requested changes
Looks awesome. Two small accessibility changes needed: reset the animation on theme.mediaQueries.reduceMotion, then add :focus styling.

2019-09-05 01:57 UTC, lachlanjc commented on src/components/Flag.js
> +    animation: none;
```suggestion
    animation: none !important;
```

2019-09-05 01:57 UTC, lachlanjc commented on src/components/Flag.js
> +      ${theme.mediaQueries.reduceMotion} {
I think you can remove this whole selector

2019-09-05 02:00 UTC, thesephist commented on src/components/Flag.js
> +      ${theme.mediaQueries.reduceMotion} {
Touche.

2019-09-05 02:06 UTC, lachlanjc commented
On a touchscreen on the homepage, if you tap the flag, it starts waving & never stops. :)

2019-09-05 02:07 UTC, lachlanjc approved these changes

2019-09-05 03:43 UTC, zanedb commented
@thesephist you and your flaggy-flag promoting ways. you are truly a rebellious Tim.

2019-09-05 04:23 UTC, thesephist commented
@zanedb haha i was hoping a fellow Tim would stumble upon this timfoolery. Worth it. 🚀

2019-09-05 04:23 UTC, merged