Add Gary!
hackclub/v2 pull request #685
Opened 2021-04-02 09:39 UTC by sampoder

2021-04-02 09:42 UTC, lachlanjc commented
#### 📝Changed routes:


| [**/team**](https://site-aqwlpyee0.hackclub.dev/team) |
|:-:|
|<a href="https://site-aqwlpyee0.hackclub.dev/team"><img src="https://images.weserv.nl?url=https://s.microlink.io/LfrcKZ3itdCVtZd2fkKsnL6ImEY_.png&w=600" alt="Screenshot of /team" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/8c0UAXxTssMH5VjR3kHXhm6x5gk_.png">(view full size)</a> |







Commit a3e86591a8c65b7095396359c5ca69c8fca2482a (https://site-aqwlpyee0.hackclub.dev).

2021-04-03 08:20 UTC, garyhtou requested changes
Thanks @sampoder!

2021-04-03 08:20 UTC, garyhtou commented on src/pages/team.js
> +          text="Gary lives in Washington and is currently completing his High Schooling. He used Hack Club Bank to form the synHacks organization and help his local community. Now, he is helping make
```suggestion
          text="Gary is an aspiring developer from Seattle who loves everything tech. After using Hack Club Bank to launch the synHacks organization and inspire students to help the global community, Gary joined Hack Club to make the product that enabled him to do great things even greater for others."
```

2021-04-03 08:20 UTC, garyhtou commented on src/pages/team.js
> +          img="/team/gary.jpeg"
```suggestion
          pronouns="he/him"
          img="/team/gary.jpeg"
```

2021-04-25 15:12 UTC, sampoder commented
Website gary is sad

2021-04-26 14:21 UTC, maxwofford approved these changes
I'm cool with this, but let's get @MelSmith104's approval on this first.

I'd also like the copy to be a bit shorter. The content is fine, but there are some filler words we can trim.

"launch the synHacks organization and inspire students to help the global community" -> "launch synHacks, a social nonprofit," or something like that

2021-04-27 01:13 UTC, sampoder commented on src/pages/team.js
> +          text="Gary is an aspiring developer from Seattle who loves everything tech. After using Hack Club Bank to launch the synHacks organization and inspire students to help the global community,
```suggestion
          text="Gary is a developer from Seattle. After using Hack Club Bank to launch the synHacks organization, a social nonprofit, Gary joined Hack Club to make the product that enabled him to do great things even greater for others."
```

2021-04-27 15:43 UTC, merged